const WA='https://wa.me/4915216767415', TG='https://t.me/xenapeptide';
const descriptions={
 'Retatrutide':'Investigational multi-receptor peptide studied for GIP, GLP-1 and glucagon receptor signaling.',
 'Tesamorelin':'Growth-hormone-releasing factor analogue investigated in metabolic and body-composition research.',
 'MOTS-C':'Mitochondrial-derived peptide investigated in cellular energy, metabolism and signaling research.',
 'Epithalon':'Short peptide investigated in cellular, aging and molecular biology research.',
 'IGF-1 LR3':'Modified IGF-1 analogue used in laboratory research on growth-factor signaling.',
 'PT-141':'Melanocortin receptor agonist investigated in neuroendocrine and receptor-signaling research.',
 'SLU-PP-332':'Small-molecule research compound investigated in metabolic and exercise-biology pathways.',
 'GHK-Cu':'Copper-binding peptide studied in extracellular matrix, skin and cellular signaling research.',
 'TB-500':'Thymosin-derived research peptide studied in cellular migration and tissue-repair pathways.',
 'BPC-157':'Peptide investigated in laboratory models of gastrointestinal, vascular and tissue-signaling pathways.',
 'CJC-1295 DAC':'Long-acting growth-hormone-releasing hormone analogue investigated in endocrine signaling research.',
 'GHRP-6':'Growth-hormone secretagogue investigated in peptide-receptor and endocrine signaling research.',
 'HCG':'Gonadotropin research material used in laboratory studies of receptor and reproductive signaling.',
 '5-Amino-1MQ':'Small-molecule research compound investigated in NNMT-related metabolic pathways.',
 'Thymosin Alpha-1':'Peptide investigated in immune signaling and cellular response research.',
 'HGH':'Human growth hormone research material for controlled laboratory investigation of growth signaling.',
 'HGH Fragment 176-191':'Growth-hormone fragment investigated in laboratory studies of metabolic signaling.',
};
let products=[];
async function loadProducts(){try{const r=await fetch('products.json');const d=await r.json();products=d.products||[];return products}catch(e){return []}}
function card(p){const desc=descriptions[p.name]||'Research compound presented for controlled scientific investigation.';const img=p.image||'images/retatrutide_10mg.jpeg';return `<article class="card"><a href="product.html?id=${encodeURIComponent(p.id)}" style="text-decoration:none;color:inherit"><span class="badge">RESEARCH ONLY</span><div class="card-img"><img src="${img}" alt="XENA PEPTIDE ${p.name}"></div><div class="card-body"><h3>${p.name}</h3><div class="what">${desc}</div><div class="meta"><b>${p.amount||'10 mg'}</b><span class="view">VIEW PRODUCT →</span></div></div></a></article>`}
function render(list,target){const el=document.getElementById(target);if(el)el.innerHTML=list.map(card).join('')||'<p>No products found.</p>'}
function filterCatalog(){const q=(document.getElementById('catalogSearch')?.value||'').toLowerCase();render(products.filter(p=>p.name.toLowerCase().includes(q)),'catalog')}
async function init(){await loadProducts();if(document.getElementById('featured'))render(products.slice(0,8),'featured');if(document.getElementById('catalog')){filterCatalog();document.getElementById('catalogSearch').addEventListener('input',filterCatalog)}const params=new URLSearchParams(location.search),id=params.get('id');if(document.getElementById('productDetail')){const p=products.find(x=>x.id===id);if(!p){document.getElementById('productDetail').innerHTML='<div class="error"><h1>Product not found</h1><a href="products.html">Back to products</a></div>';return}renderDetail(p)}document.getElementById('siteSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){location.href='products.html?search='+encodeURIComponent(e.target.value)}})}
function renderDetail(p){const d=descriptions[p.name]||'Research compound presented for controlled scientific investigation.';const img=p.image||'images/retatrutide_10mg.jpeg';document.title=`${p.name} ${p.amount||''} | XENA PEPTIDE`;document.getElementById('productDetail').innerHTML=`<main class="detail-wrap"><div class="crumb">Home　›　Products　›　${p.name} ${p.amount||''}</div><section class="detail"><div class="detail-media"><img src="${img}" alt="${p.name} ${p.amount||''}"></div><div class="detail-copy"><p class="eyebrow">RESEARCH PEPTIDE</p><h1>${p.name} ${p.amount||''}</h1><span class="amount">${p.amount||'10 mg'}</span><div class="price">€${Number(p.price||0).toFixed(2)}</div><div class="notice">◈ Research Use Only — Not for human or veterinary use.</div><div class="specs"><div><span>Product Name</span><b>${p.name}</b></div><div><span>Amount</span><b>${p.amount||'10 mg'}</b></div><div><span>Form</span><b>Lyophilized powder</b></div><div><span>Purity</span><b>${p.purity||'See COA'}</b></div><div><span>Research Category</span><b>Laboratory research</b></div></div><div class="contact-box"><h3>Interested in this product?</h3><p>Contact XENA PEPTIDE directly for product information and available documentation.</p><div class="contact-buttons"><a href="${WA}" target="_blank" rel="noopener">WhatsApp →</a><a href="${TG}" target="_blank" rel="noopener">Telegram →</a></div></div></div></section><section class="description-grid"><div><h3>What is it?</h3><p>${d}</p><h3>Research Presentation</h3><ul><li>Research-use-only catalogue entry</li><li>Lyophilized presentation where applicable</li><li>Purity information shown where documented</li></ul></div><div><h3>Research Focus</h3><p>${d}</p><p>Scientific investigation should be performed under appropriate laboratory protocols and applicable regulations.</p></div><div><h3>Handling & Documentation</h3><p>Refer to the product documentation and applicable laboratory procedures. Contact us for available COA information.</p><p><b>For laboratory research only.</b></p></div></section></main>`}
init();
